### PR TITLE
Silence warning

### PR DESCRIPTION
**Pull request by noseglid**
Silence deprecation warning and include travis

### CODE REVIEW

**Review by domszyn — APPROVED** [review]

**Comment by domszyn** [comment]
These warnings have been bugging me for a while, thanks for taking them out 👍

**Comment by domszyn** [comment]
Build is failing due to the outdated Yarn version picked by Travis. Is there any way to specify it explicitly?

**Comment by noseglid** [comment]
Don't think it's because of the version. it fails with errors;
```
error An unexpected error occurred: "https://registry.yarnpkg.com/csstype/-/csstype-2.5.3.tgz: Request failed \"429 Too Many Requests\"".
```
so looks like some request limit is reached.

I restarted the build now (~1hr later) and it worked. Hopefully just unlucky

**Comment by domszyn** [comment]
Oh yes, I mistook Node warnings for errors. Still would be nice to up Yarn to 1.7

**Comment by noseglid** [comment]
I agree, changed it to manually install 1.7

**Pull request merged**
